server:
  port: 18888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MSA-Service-12th/config
          search-paths:
          - common
          - '{application}'
          - '{application}/{profile}'
          default-label: dev

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:18761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics